In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [36]:
data = pd.read_csv("spotify_millsongdata.csv")
df = pd.DataFrame(data)
df.tail(10)

,artist,song,link,text
57640,Zebrahead,The Setup,/z/zebrahead/the+setup_10198494.html,Lie to me \r\nTell me that everything will be...
57641,Ziggy Marley,Freedom Road,/z/ziggy+marley/freedom+road_20531174.html,"That's why I'm marching, yes, I'm marching, \..."
57642,Ziggy Marley,Friend,/z/ziggy+marley/friend_20673508.html,[Chorus] \r\nI wanna thank you for the things...
57643,Ziggy Marley,G7,/z/ziggy+marley/g7_20531173.html,Seven richest countries in the world \r\nThem...
57644,Ziggy Marley,Generation,/z/ziggy+marley/generation_20531171.html,Many generation have passed away \r\nFighting...
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [37]:
df.shape

(57650, 4)

In [38]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [39]:
df.shape

(57650, 4)

In [40]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [41]:
df["text"][0]

"Look at her face, it's a wonderful face  \r\nAnd it means something special to me  \r\nLook at the way that she smiles when she sees me  \r\nHow lucky can one fellow be?  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?  \r\n  \r\nAnd when we go for a walk in the park  \r\nAnd she holds me and squeezes my hand  \r\nWe'll go on walking for hours and talking  \r\nAbout all the things that we plan  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?\r\n\r\n"

In [43]:
df = df.sample(5000).drop("link" , axis = 1).reset_index(drop = True)

In [47]:
df.shape

(5000, 3)

now cleaning the text  cleaning process

## CREATING COMPELETE NLTK PIPELINE

In [48]:
import nltk
import string

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer

In [49]:
df["text"].head()

0    (Dolly Parton)  \r\nI know this dress I'm wear...
1    (After Love Is Gone)  \r\n  \r\n? Saying what'...
2    And if I'm wasting my time  \r\nThen nothing c...
3    Lord I stand in the midst of a multitude  \r\n...
4    I don't have much to say.  \r\nThought I'd cal...
Name: text, dtype: object

In [50]:
df["text"] = df["text"].str.lower().replace(r"^\w\s" , "").replace(r"\n", " ",regex = True)

In [51]:
#now convert the text the token
df.tail(5)

,artist,song,text
4995,Nitty Gritty Dirt Band,Oh What A Love,"oh what a love, that'll bind the wounds of a l..."
4996,Dave Matthews Band,I'm Over You,when was the point that you showed- \r move o...
4997,Thin Lizzy,Having A Good Time,"me and my buddies, we're going to get drunk \..."
4998,Venom,Dead Love,at night the corpses rise \r and leave a sren...
4999,"Harry Connick, Jr.",I've Got A Great Idea,i've got a great idea \r and wouldn't you lik...

In [52]:
Stemmer = PorterStemmer()

In [53]:
#use predefine function  convert all the text into token using nltk
def token(txt):
    token = nltk.word_tokenize(txt)
    a = [Stemmer.stem(w) for w in token ]
    return " ".join(a)

In [54]:
token("you are very beautiful , beauty")

'you are veri beauti , beauti'

In [55]:
df["text"] = df["text"].apply(lambda x : token(x))

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
tfid = TfidfVectorizer(analyzer= "word" , stop_words= "english" , tokenizer= token )

In [57]:
matrix = tfid.fit_transform(df["text"])

C:\Users\User\AppData\Roaming\Python\Python313\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
C:\Users\User\AppData\Roaming\Python\Python313\site-packages\sklearn\feature_extraction\text.py:402: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens [' ', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'] not in stop_words.
  warnings.warn(

In [58]:
similar =  cosine_similarity(matrix)

In [59]:
similar[0]

array([1.        , 0.9624469 , 0.98764327, ..., 0.98135665, 0.97777916,
       0.98604998], shape=(5000,))

In [60]:
#now make recommendation system
df["song"] = df["song"].str.strip()
df[df["song"] == "Waiting For The Man"].index[0]

np.int64(3575)

In [65]:
def recommender(song_name) :
    song = []
    idx = df[df["song"] == song_name].index[0]
    distance = sorted(list(enumerate(similar[idx])) , reverse = True , key = lambda x: x[1])

    for s_id in distance[1:10]:
        song.append(df.iloc[s_id[0]].song)

    return song

In [66]:
recommender("Waiting For The Man")

['Gone',
 'Big Brown Eyes',
 "Amazin'",
 "Don't Let It End",
 'Surefire',
 'Momma Knows',
 "I Wish I Wasn't",
 'Kingdome Come',
 'Bananas']